<?php
namespace WarehouseCore\Config;

final readonly class RepositoryConfig {
    use ConfigHelper;
    public function __construct(
        public string $area,
        public string $zone,
        public string $rack_placement,
        public string $container_placement,
        public string $item_placement,
        public string $stock_placement,
        public string $rack,
        public string $shelf,
        public string $container,
        public string $item,
        public string $stock,
        public string $physical_tag,
        public string $item_processing_step,
        public string $part_processing_step,
        public string $area_name,
        public string $zone_name,
        public string $rack_name,
        public string $part,
        public string $part_number,
        public string $part_name,
        public string $vehicle,
        public string $part_photo,
        public string $item_photo,
        public string $stock_photo,
        public string $vehicle_photo,
        public string $part_video,
        public string $item_video,
        public string $stock_video,
        public string $vehicle_video,
        public string $stored_file,
        public string $rack_placement_archive,
        public string $container_placement_archive,
        public string $item_placement_archive,
        public string $stock_placement_archive,
        public string $rack_movement_archive,
        public string $container_movement_archive,
        public string $item_movement_archive,
        public string $stock_movement_archive,
        public string $item_sales_archive,
        public string $stock_sales_archive,
        public string $journal,
        public string $owner,
        public string $area_access,
        public string $role,
        public string $provider,
        public string $user,
        public string $user_identity,
    ) { }

    public static function fromRaw(
        array $raw
    ): self {
        return new self(
            area: self::requiredString($raw, 'Area'),
            zone: self::requiredString($raw, 'Zone'),
            rack_placement: self::requiredString($raw, 'RackPlacement'),
            container_placement: self::requiredString($raw, 'ContainerPlacement'),
            item_placement: self::requiredString($raw, 'ItemPlacement'),
            stock_placement: self::requiredString($raw, 'StockPlacement'),
            rack: self::requiredString($raw, 'Rack'),
            shelf: self::requiredString($raw, 'Shelf'),
            container: self::requiredString($raw, 'Container'),
            item: self::requiredString($raw, 'Item'),
            stock: self::requiredString($raw, 'Stock'),
            physical_tag: self::requiredString($raw, 'PhysicalTag'),
            item_processing_step: self::requiredString($raw, 'ItemProcessingStep'),
            part_processing_step: self::requiredString($raw, 'PartProcessingStep'),
            area_name: self::requiredString($raw, 'AreaName'),
            zone_name: self::requiredString($raw, 'ZoneName'),
            rack_name: self::requiredString($raw, 'RackName'),
            part: self::requiredString($raw, 'Part'),
            part_number: self::requiredString($raw, 'PartNumber'),
            part_name: self::requiredString($raw, 'PartName'),
            vehicle: self::requiredString($raw, 'Vehicle'),
            part_photo: self::requiredString($raw, 'PartPhoto'),
            item_photo: self::requiredString($raw, 'ItemPhoto'),
            stock_photo: self::requiredString($raw, 'StockPhoto'),
            vehicle_photo: self::requiredString($raw, 'VehiclePhoto'),
            part_video: self::requiredString($raw, 'PartVideo'),
            item_video: self::requiredString($raw, 'ItemVideo'),
            stock_video: self::requiredString($raw, 'StockVideo'),
            vehicle_video: self::requiredString($raw, 'VehicleVideo'),
            stored_file: self::requiredString($raw, 'StoredFile'),
            rack_placement_archive: self::requiredString($raw, 'RackPlacementArchive'),
            container_placement_archive: self::requiredString($raw, 'ContainerPlacementArchive'),
            item_placement_archive: self::requiredString($raw, 'ItemPlacementArchive'),
            stock_placement_archive: self::requiredString($raw, 'StockPlacementArchive'),
            rack_movement_archive: self::requiredString($raw, 'RackMovementArchive'),
            container_movement_archive: self::requiredString($raw, 'ContainerMovementArchive'),
            item_movement_archive: self::requiredString($raw, 'ItemMovementArchive'),
            stock_movement_archive: self::requiredString($raw, 'StockMovementArchive'),
            item_sales_archive: self::requiredString($raw, 'ItemSalesArchive'),
            stock_sales_archive: self::requiredString($raw, 'StockSalesArchive'),
            journal: self::requiredString($raw, 'Journal'),
            owner: self::requiredString($raw, 'Owner'),
            area_access: self::requiredString($raw, 'AreaAccess'),
            role: self::requiredString($raw, 'Role'),
            provider: self::requiredString($raw, 'Provider'),
            user: self::requiredString($raw, 'User'),
            user_identity: self::requiredString($raw, 'UserIdentity'),
        );
    }
}