<?php

return [
    'AddAreaName' => 'add_area_name',
    'SetPrimaryAreaName' => 'set_primary_area_name',
    'RemoveAreaName' => 'remove_area_name',
    'GrantAreaAccess' => 'grant_area_access',
    'RevokeAreaAccess' => 'revoke_area_access',
    'CreateArea' => 'create_area',
    'ActivateArea' => 'activate_area',
    'MarkAreaAsCrowded' => 'mark_area_as_crowded',
    'ArchiveArea' => 'archive_area',

    'AddZoneName' => 'add_zone_name',
    'SetPrimaryZoneName' => 'set_primary_zone_name',
    'RemoveZoneName' => 'remove_zone_name',
    'CreateZone' => 'create_zone',
    'ActivateZone' => 'activate_zone',
    'MarkZoneaAsCrowded' => 'mark_zone_as_crowded',
    'ArchiveZone' => 'archive_zone',

    'ListArea' => 'list_area',
    'ListAreaNames' => 'list_area_names',
    'ListZoneByArea' => 'list_zone_by_area',
    'ListZoneNames' => 'list_zone_names',
    'ListUser' => 'list_user',
    'ListUserNames' => 'list_user_names',
    'ListUserIdentities' => 'list_user_identities',
    'ListRack' => 'list_rack',
    'ListRackNames' => 'list_rack_names',
    'ListRackByArea' => 'list_rack_by_area',
    'ListRackByZone' => 'list_rack_by_zone',

    'CreateUser' => 'create_user',
    'ActivateUser' => 'activate_user',
    'ArchiveUser' => 'archive_user',
    'AssignUserRole' => 'assign_user_role',
    'DismissUserRole' => 'dismiss_user_role',
    'AddUserIdentity' => 'add_user_identity',
    'RemoveUserIdentity' => 'remove_user_identity',
    'AddUserName' => 'add_user_name',
    'SetPrimaryUserName' => 'set_primary_user_name',
    'RemoveUserName' => 'remove_user_name',

    'RegisterRack' => 'register_rack',
    'ActivateRack' => 'activate_rack',
    'MarkRackAsCrowded' => 'mark_rack_as_crowded',
    'ArchiveRack' => 'archive_rack',
    'PopulateRack' => 'populate_rack',
    'PlaceRackToArea' => 'place_rack_to_area',
    'PlaceRackToZone' => 'place_rack_to_zone',
    'MoveRackToArea' => 'move_rack_to_area',
    'MoveRackToZone' => 'move_rack_to_zone',
    'AddRackName' => 'add_rack_name',
    'SetPrimaryRackName' => 'set_primary_rack_name',
    'RemoveRackName' => 'remove_rack_name',

    'CreatePhysicalTag' => 'create_physical_tag',
    'CreateContainer' => 'create_container',
    'AssignPhysicalTag' => 'assign_physical_tag',
    'CreateStock' => 'create_stock',
    'PlaceItem' => 'place_item'
];