<?php 

return [
    'Location'              => 'locations',
    'ContainerPlacement'    => 'container_placements',
    'ItemPlacement'         => 'item_placements',
    'StockPlacement'        => 'stock_placements',
    'Container'             => 'containers',
    'Item'                  => 'items',
    'Stock'                 => 'stock',
    'ItemProcessingStep'    => 'item_processing_steps',
    'Part'                  => 'parts',
    'PartAlias'             => 'part_aliases',
    'Vehicle'               => 'vehicles',
    'StoredFile'            => 'stored_files',
    'PartPhoto'             => 'part_photos',
    'ItemPhoto'             => 'item_photos',
    'StockPhoto'            => 'stock_photos',
    'VehiclePhoto'          => 'vehicle_photos',
    'Telemetry'             => 'telemetry',
    'ItemSalesArhive'       => 'item_sales_archive',
    'StockSalesArhive'      => 'stock_sales_archive',
    'Role'                  => 'roles',
    'User'                  => 'users',
    'UserIdentity'          => 'user_identities',
    'Owner'                 => 'owners',
    'PhysicalTag'           => 'physical_tags',
];
